# Generated by Django 3.0 on 2020-09-16 09:27

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Job',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('task_id', models.CharField(max_length=255, unique=True)),
                ('date_created', models.DateTimeField(auto_now_add=True, db_index=True, help_text='Datetime field when the task result was created in UTC', verbose_name='Created DateTime')),
            ],
        ),
    ]
