# Generated by Django 3.2 on 2022-09-22 12:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('geospaas_rest_api', '0002_auto_20201019_1331'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ConvertJob',
        ),
        migrations.CreateModel(
            name='HarvestJob',
            fields=[
            ],
            options={
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('geospaas_rest_api.job',),
        ),
        migrations.CreateModel(
            name='ConvertJob',
            fields=[
                ('job_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='geospaas_rest_api.job')),
            ],
            bases=('geospaas_rest_api.job',),
        ),
        migrations.CreateModel(
            name='IDFConvertJob',
            fields=[
            ],
            options={
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('geospaas_rest_api.convertjob',),
        ),
        migrations.CreateModel(
            name='SyntoolConvertJob',
            fields=[
            ],
            options={
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('geospaas_rest_api.convertjob',),
        ),
    ]
