# Generated by Django 3.2 on 2023-03-15 14:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('geospaas_rest_api', '0003_auto_20220922_1205'),
    ]

    operations = [
        migrations.DeleteModel(
            name='IDFConvertJob',
        ),
        migrations.DeleteModel(
            name='SyntoolConvertJob',
        ),
        migrations.CreateModel(
            name='SyntoolCleanupJob',
            fields=[
            ],
            options={
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('geospaas_rest_api.job',),
        ),
        migrations.DeleteModel(
            name='ConvertJob',
        ),
        migrations.CreateModel(
            name='ConvertJob',
            fields=[
            ],
            options={
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('geospaas_rest_api.job',),
        ),
    ]
