# Generated by Django 3.2 on 2023-10-23 12:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('geospaas_rest_api', '0004_auto_20230315_1450'),
    ]

    operations = [
        migrations.AlterField(
            model_name='job',
            name='task_id',
            field=models.CharField(help_text='ID of the last task in the job', max_length=255, unique=True),
        ),
    ]
